### ISSUE TITLE
Separar parte de validação em novo repo

### ISSUE THREAD

**Issue by nazareno** [dadosjusbr/analises#14]
Esse repo hoje mistura código de validação dos dados produzidos pelo dadosjusbr com código de análise. Acho que já podemos ter um outro repo chamado validacao-uso ou algo assim que tem o código de fetch como o nosso, um transform que apenas concatena os arquivos (com era antes de [uma modificação que fiz há pouco](https://github.com/dadosjusbr/analises/commit/610c9ff9e08fb60575985a9eb67cd6b5f8920efe)) e reports que focam em encontrar inconsistências nos dados e listá-los para o time de coletores. 

Nesse repo atual ficariam o código que temos hoje com o transform para relatórios e as análises descritivas usando os dados sem se preocupar com validá-los.

**Comment by diegooalmeida** [comment]
Novo repositório [aqui](https://github.com/dadosjusbr/validacao-uso).
